export enum UsersEvents {
  FOLLOW_USER = "FOLLOW-USER",
  UNFOLLOW_USER = "UNFOLLOW-USER",
  SET_USERS = "SET-USERS",
  SET_CURRENT_PAGE = `SET-CURRENT-PAGE`,
  SET_TOTAL_USERS_COUNT = "SET-TOTAL-USERS-COUNT",
  TOGGLE_IS_FETCHING = "TOGGLE-IS-FETCHING",
  TOGGLE_FOLLOWING_PROGRESS = "TOGGLE-FOLLOWING-PROGRESS",
}

export enum ProfileEvents {
  ADD_POST = "ADD-POST",
  UPDATE_NEW_POST_TEXT = "UPDATE-NEW-POST-TEXT",
  SET_USER_PROFILE = "SET-USER-PROFILE",
}

export enum DialogsEvents {
  ADD_MESSAGE = "ADD-MESSAGE",
  UPDATE_NEW_MEESSAGE_TEXT = "UPDATE-NEW-MESSAGE-TEXT",
}

export enum AuthEvents {
  SET_USER_DATA = "SET-USER-DATA",
}
